### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by 00-Python** [UndeadSec/Idisagree#5]
When You run the runontarget.py i get this error message.

$python3 RunOnTarget.py 
Traceback (most recent call last):
  File "RunOnTarget.py", line 3, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'

Any Help?
Thanks

**Comment by 00-Python** [comment]
Well I figuered out i just had to pip3 discord.py and that solved that but now i get a different error after it starts correctly.

Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/jw/.local/lib/python3.7/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "RunOnTarget.py", line 15, in on_message
    await client.send_message(message.channel, msg)
AttributeError: 'Client' object has no attribute 'send_message'

**Comment by weuroi578** [comment]
did anyone find a fix tor the previous comment?

**Comment by FrxstyS3c** [comment]
I have the same error about channel msg with RunOnTarget.py

Ignoring exception in on_message
Traceback (most recent call last):
File "/home/jw/.local/lib/python3.7/site-packages/discord/client.py", line 270, in _run_event
await coro(*args, **kwargs)
File "RunOnTarget.py", line 15, in on_message
await client.send_message(message.channel, msg)
AttributeError: 'Client' object has no attribute 'send_message'

**Comment by swagkarna** [comment]
> I have the same error about channel msg with RunOnTarget.py
> 
> Ignoring exception in on_message
> Traceback (most recent call last):
> File "/home/jw/.local/lib/python3.7/site-packages/discord/client.py", line 270, in _run_event
> await coro(*args, **kwargs)
> File "RunOnTarget.py", line 15, in on_message
> await client.send_message(message.channel, msg)
> AttributeError: 'Client' object has no attribute 'send_message'

Just edit RunOnTarget.py and enter the code below
await message.channel.send(msg)
Note:Remove this command if it works just inform me

**Comment by Znunu** [comment]
I forked the repository, fixed the bug, fixed some more bugs and made it possible to navigate the filesystem
https://github.com/Znunu/Idisagree
